### ISSUE TITLE
FarmBeats Not Communicating with Azure

### ISSUE THREAD

**Issue by MukulShukla** [farmbeatslabs/studentkit#4]
Here are the emails that describe the issue so far -

We were trying to set up the kit again, and we seem to have hit a dead end. We have a few questions for you, and we're hoping you could help us out.

Here is what we already did -
1. We set up the OS on the board. Connected the sensors. The device boots up normally.
2. It shows up in the IOT Dashboard as a discovered device. We're able to connect to Device Portal and PowerShell to talk to the device.
3. We got the device registered and received our Azure IOT Central URL.

**The problem is that the device isn't communicating with the Azure services.** There is probably a way to enter this Azure IoT central URL somewhere on maybe the device portal but we couldn't get it working.

This is also because we were following the tutorials on GitHub but these steps are unclear -

https://github.com/farmbeatslabs/studentkit/blob/master/Indoor-m1/3_Configure_your_Azure_IoT_Central_Cloud_Service.md

What we also know
---------------------

Definitely, we're connected to the internet ( and we have the correct deviceId)

We also have installed the Sensor application software -

Device Details
----------------
Sent via email

**Comment by MukulShukla** [comment]
Also, our device gets discovered when connected to a PC but even the "Windows IOT remote client", hangs when we select the device. Not sure if we're meant to be doing this. We just thought that may be device can just locally send us values, if it's not able to connect to the cloud.

**Comment by JT73** [comment]
HI Mukul, 

Thanks for logging your issue and being the first ever! We would love to help you troubleshoot and get you FarmBeats Student Kit going. 

First though, it might not be a good idea to provide your Device details in the public issues forum. After logging your issue here, if you need to supply device or user specific details you can send additional details to our support@farmbeatslabs.com alias, 

Now, for your issue the most common thing that is overlooked is getting the right MAC address to use as the Device ID. Check that you have the Ethernet LAN device address. You don't need to use the LAN port for your internet connection but you do need to use that as the unique ID. 

![image](https://user-images.githubusercontent.com/3819168/54452740-1b54be00-4713-11e9-804a-245a183a60eb.png)

Please let us know how you get on.
Thanks
Jay

**Comment by MukulShukla** [comment]
We were using the Wireless LAN MAC address. We would want to switch to the LAN MAC address now. Does this mean we should do the registration part again?

**Comment by MukulShukla** [comment]
We registered with the new ID as a new device and all is good and working. Thanks again for helping us out.
